version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
